### ISSUE TITLE
Single-quote/apostrophe within double-quotes causing issues

### ISSUE THREAD

**Issue by dgirgenti** [eparisio/st3-jstl-syntax-highlight#1]
I have the following line of code in a JSP/JSTL file:
`<c:set var="myVar" value="${someVar}'s" scope="request" />`

This is causing the rest of the document (or, up to the next single-quote) to display in the string color (yellow/white for Monokai).

The default ST3 JSP syntax highlighting does not have an issue with this. Ideally, I should be able to do this without using an `&apos;`, but that is the only way to avoid this for now.

Thanks!

**Comment by eparisio** [comment]
Fixed the nested problem, thanks for reporting.

It is available on the last release, already drafted for package control.

**Comment by dgirgenti** [comment]
Awesome! Thanks for taking care of that so quick.
