### ISSUE TITLE
script-tag based templating messes up jstl syntax coloring

### ISSUE THREAD

**Issue by y-a-v-a** [eparisio/st3-jstl-syntax-highlight#2]
Hi, the syntax coloring of jstl messes up the view when using HTML-based templates within script tags.

```html
<script type="text/x-template">
  <div class="some-template"></div>
</script>
```

The upper image show the JSP syntax as part of the Java syntax package. The lower image shows the JSTL-syntax package.

![syntax-jsp](https://cloud.githubusercontent.com/assets/375507/20671335/3bae1464-b57d-11e6-9fe6-4bd26f51f766.png)
![syntax-jstl](https://cloud.githubusercontent.com/assets/375507/20671336/3bae1414-b57d-11e6-8f73-3d31f639e342.png)

Would be great if this could be fixed.
Regards,
Vincent

**Comment by eparisio** [comment]
Fixed the main wrapping.
edits already live.
there are some others case on nesting with javascript code, that will be fixed

**Comment by y-a-v-a** [comment]
Greatly appreciated! Thanks!
