### ISSUE TITLE
Error loading syntax file "Packages/JSTL syntax/jstl.tmLanguage": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

### ISSUE THREAD

**Issue by shmdhussain** [eparisio/st3-jstl-syntax-highlight#4]
When I start the sublime text with jsp or tag file getting the following error

> Error loading syntax file "Packages/JSTL syntax/jstl.tmLanguage": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

Please see the screenshot

![screen shot 2018-10-28 at 15 50 47](https://user-images.githubusercontent.com/4039657/47615568-ef210380-dac9-11e8-805b-96b50a8bdcc4.png)

**Comment by eparisio** [comment]
Hi @shmdhussain 

what version of sublime you have?

**Comment by shmdhussain** [comment]
@eparisio thanks for for your help...I found out the root cause for this issue by turning off all packages and turned on one by one ...then I found that there is one package called ES6 JavaScript next which is causing this issue. I disabled that now , everything seems ok now....

**Comment by shmdhussain** [comment]
@eparisio Thanks for your plugin...it helped me save lot of my time

**Comment by eparisio** [comment]
Hi @shmdhussain 

i was looking to the issue https://github.com/jonschlinkert/sublime-markdown-extended/issues/141

it seems to be linked on differente packages, you can try to update sublime if you haven'd done it.

**Comment by shmdhussain** [comment]
Yes you are right ...issue is with "JavaScript next - ES6 Syntax" package
